### ISSUE TITLE
Netscape Bookmark format

### ISSUE THREAD

**Issue by marc0janssen** [TechseriesBNX/Navigating-Apple#21]
Hi,

Is there a specific reason why the HTML formatting is still in Netscape Bookmark format?

Probably for being portable with other software?

Reason asking is that this format is  from 1994. The Netscape Bookmark format, while well-formed in its own right, does not fully comply with modern HTML standards.

Best, 
Marco

By the way, not sure if we are suppose to use the English language for this project.

**Comment by TechseriesBNX** [comment]
It's an export from Safari. We strive to make it easy to import and keep up to date. The easiest way to achieve this is using the bookmarks.html format. I know some typo's have been added over time - updating them today. 

English is perfectly fine. This is in international effort. We have friends from all over the world looking into / adding to / ... the project.

**Comment by marc0janssen** [comment]
Thanks for clarifying. I was just wondering, but as I suspected it's to stay compatible with browsers' bookmarks.
For me this can be closed. 
Have a nice day!
